
function myui

scrnsz=get(0,'ScreenSize');
janela=figure('Name','WELCOME! Start defining your variable','NumberTitle','off','Position',[1,1,scrnsz(3)*.65,scrnsz(4)],'color','w');
set(findobj(janela),'Units','Normalized');

%MAke radio buttons for choosing BRAIN PART
brain_part = uibuttongroup(janela,'Visible','on',...
                  'Position',[.01 .77 .2 .22]);
                  %'SelectionChangedFcn',@bselection;
              
set (0, 'DefaultUIControlFontSize', 18);
                  uicontrol(brain_part,...
                      'Style','text',...
                      'String', 'Brain part:',...
                      'ForegroundColor',[1 0 .3],...
                      'Units', 'normalized',...
                      'Position',[.025 .6 1 .3]);
                  
                  
                  % Create three radio buttons in the button group.
                  set (0, 'DefaultUIControlFontSize', 12);
brain_part_ans = uicontrol(brain_part,'Style','radiobutton',...
                  'String','Caudate Putamen',...
                  'Units', 'normalized',...
                  'Position',[.05 .4 1 .2],...
                  'Tag', 'CP',...
                  'HandleVisibility','off');
              
brain_part_ans = uicontrol(brain_part,'Style','radiobutton',...
                  'String','Substantia Nigra',...
                  'Units', 'normalized',...
                  'Position',[0.05 0.15 1 .2],...
                  'Tag', 'SN',...
                  'HandleVisibility','off');

%MAke radio buttons for choosing MARKER
marker = uibuttongroup(janela,'Visible','on',...
                  'Position',[.01 .46 .2 .30],...
                  'BackgroundColor',[.85 .85 .85]);
                  %'SelectionChangedFcn',@bselection);
              
set (0, 'DefaultUIControlFontSize', 18);
                  uicontrol(marker,...
                      'Style','text',...
                      'ForegroundColor',[1 0 .3],...
                      'BackgroundColor',[.85 .85 .85],...
                      'String', 'Marker:',...
                      'Units', 'normalized',...
                      'Position',[.025 .6 1 .3]);
               
                  
                  
                  % Create three radio buttons in the button group.
                  set (0, 'DefaultUIControlFontSize', 12);
marker_ans = uicontrol(marker,'Style','radiobutton',...
                  'String','D1',...
                  'Units', 'normalized',...
                  'Position',[.05 .5 1 .2],...
                  'Tag', 'D1',...
                  'BackgroundColor',[.85 .85 .85],...
                  'HandleVisibility','off');
              
marker_ans = uicontrol(marker,'Style','radiobutton',...
                  'String','D2',...
                  'Units', 'normalized',...
                  'Position',[.05 .3 1 .2],...
                  'Tag', 'D2',...
                  'BackgroundColor',[.85 .85 .85],...
                  'HandleVisibility','off');

marker_ans = uicontrol(marker,'Style','radiobutton',...
                  'String','DARPP',...
                  'Units', 'normalized',...
                  'Position',[.05 .1 1 .2],...
                  'Tag', 'DARPP',...
                  'BackgroundColor',[.85 .85 .85],...
                  'HandleVisibility','off');
              
             
              
              
              %MAke radio buttons for choosing setup GROUPS
group = uibuttongroup(janela,'Visible','on',...
                  'Position',[.01 .065 .2 .38],...
                  'BackgroundColor',[.8 .8 .8]);
                  %'SelectionChangedFcn',@bselection);
              
set (0, 'DefaultUIControlFontSize', 18);
                  uicontrol(group,...
                      'Style','text',...
                      'ForegroundColor',[1 0 .3],...
                      'BackgroundColor',[.8 .8 .8],...
                      'String', 'Group(s):',...
                      'Units', 'normalized',...
                      'Position',[.025 .6 1 .3]);
                  
                  
                  % Create three checkbox buttons in the button group.
                  set (0, 'DefaultUIControlFontSize', 12);
ylcr_ans = uicontrol(group,'Style','checkbox',...
                  'String','Young LCR',...
                  'Units', 'normalized',...
                  'Position',[.05 .6 1 .2],...
                  'Tag', 'ylcr',...
                  'BackgroundColor',[.8 .8 .8],...
                  'HandleVisibility','on');
              
yhcr_ans = uicontrol(group,'Style','checkbox',...
                  'String','Young HCR',...
                  'Units', 'normalized',...
                  'Position',[.05 .45 1 .2],...
                  'Tag', 'yhcr',...
                  'BackgroundColor',[.8 .8 .8],...
                  'HandleVisibility','on');

olcr_ans = uicontrol(group,'Style','checkbox',...
                  'String','Old LCR',...
                  'Units', 'normalized',...
                  'Position',[.05 .3 1 .2],...
                  'Tag', 'olcr',...
                  'BackgroundColor',[.8 .8 .8],...
                  'HandleVisibility','on');
              
ohcr_ans = uicontrol(group,'Style','checkbox',...
                  'String','Old HCR',...
                  'Units', 'normalized',...
                  'Position',[.05 .15 1 .2],...
                  'Tag', 'ohcr',...
                  'BackgroundColor',[.8 .8 .8],...
                  'HandleVisibility','on');
              
              
 %MAke radio buttons for choosing VARIABLE GROUP
var_grp = uibuttongroup(janela,'Visible','on',...
                  'Position',[.22 .739 .2 .25],...
                  'BackgroundColor',[.75 .75 .75]);
                  %'SelectionChangedFcn',@bselection);
              
set (0, 'DefaultUIControlFontSize', 18);
                  uicontrol(var_grp,...
                      'Style','text',...
                      'ForegroundColor',[1 0 .3],...
                      'BackgroundColor',[.75 .75 .75],...
                      'String', 'Variable type:',...
                      'Units', 'normalized',...
                      'Position',[.025 .65 1 .3]);
                  
                  
   
                 % Create three radio buttons in the button group.
                  set (0, 'DefaultUIControlFontSize', 12);
              
var_grp_ans = uicontrol(var_grp,'Style','radiobutton',...
                  'String','Somata',...
                  'Units', 'normalized',...
                  'Position',[.05 .55 1 .2],...
                  'Tag', 'somata',...
                  'BackgroundColor',[.75 .75 .75],...
                  'ForegroundColor',[0 0 .5],...
                  'HandleVisibility','off');

var_grp_ans = uicontrol(var_grp,'Style','radiobutton',...
                  'String','Axon signal',...
                  'Units', 'normalized',...
                  'Position',[.05 .35 1 .2],...
                  'Tag', 'axon_sgn',...
                  'BackgroundColor',[.75 .75 .75],...
                  'ForegroundColor',[0 .5 0],...
                  'HandleVisibility','off');
             
var_grp_ans = uicontrol(var_grp,'Style','radiobutton',...
                  'String','Soma colocalization',...
                  'Units', 'normalized',...
                  'Position',[.05 .15 1 .2],...
                  'Tag', 'coloc',...
                  'BackgroundColor',[.75 .75 .75],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
              
              
              
              %MAke radio buttons for choosing SPECIFIC VARIABLE
spcif_var = uibuttongroup(janela,'Visible','on',...
                  'Position',[.43 .06 .55 .93],...
                  'BackgroundColor',[.70 .70 .70]);
                  %'SelectionChangedFcn',@bselection);
              
set (0, 'DefaultUIControlFontSize', 18);
                  uicontrol(spcif_var,...
                      'Style','text',...
                      'ForegroundColor',[1 0 .3],...
                      'BackgroundColor',[.70 .70 .70],...
                      'String', 'Specific variable:',...
                      'Units', 'normalized',...
                      'Position',[.001 .65 1 .3]);
                  
                  
   
                 % Create three radio buttons in the button group.
                  set (0, 'DefaultUIControlFontSize', 12);
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Average volume of marked body',...
                  'Units', 'normalized',...
                  'Position',[.05 .85 1 .03],...
                  'Tag', 'volume',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[0 0 .5],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Total number of bodies',...
                  'Units', 'normalized',...
                  'Position',[.05 .82 1 .03],...
                  'Tag', 'number',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[0 0 .5],...
                  'HandleVisibility','off');

spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Number corrected for voxels (some subjects had less slices)',...
                  'Units', 'normalized',...
                  'Position',[.05 .79 1 .03],...
                  'Tag', 'number_Corrected_for_voxels',...
                  'ForegroundColor',[0 0 .5],...
                  'BackgroundColor',[.70 .70 .70],...
                  'HandleVisibility','off');
             
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Mean (with somata)',...
                  'Units', 'normalized',...
                  'Position',[.05 .74 1 .03],...
                  'Tag', 'mean_with_somata',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[0 .5 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Mean (without somata)',...
                  'Units', 'normalized',...
                  'Position',[.05 .71 1 .03],...
                  'Tag', 'mean_without_somata',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[0 .5 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Mean (corrected for voxels)',...
                  'Units', 'normalized',...
                  'Position',[.05 .68 1 .03],...
                  'Tag', 'MEAN_Corrected_for_voxels',...
                  'ForegroundColor',[0 .5 0],...
                  'BackgroundColor',[.70 .70 .70],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Mean (with somata corrected for voxels)',...
                  'Units', 'normalized',...
                  'Position',[.05 .65 1 .03],...
                  'Tag', 'MEAN_Corrected_for_voxels_somata',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[0 .5 0],...
                  'HandleVisibility','off');  
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Mean (without somata corrected for voxels)',...
                  'Units', 'normalized',...
                  'Position',[.05 .62 1 .03],...
                  'Tag', 'MEAN_Corrected_for_voxels_NO_somata',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[0 .5 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Mean (corrected for voxels and correction factor)',...
                  'Units', 'normalized',...
                  'Position',[.05 .59 1 .03],...
                  'Tag', 'MEAN_Corrected_for_voxels_and_correction_factor',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[0 .5 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Mean (with somata corrected for voxels and correction factor)',...
                  'Units', 'normalized',...
                  'Position',[.05 .56 1 .03],...
                  'Tag', 'MEAN_Corrected_for_voxels_and_correction_factor_somata',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[0 .5 0],...
                  'HandleVisibility','off');  
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Mean (without somata corrected for voxels and correction factor)',...
                  'Units', 'normalized',...
                  'Position',[.05 .53 1 .03],...
                  'Tag', 'MEAN_Corrected_for_voxels_and_correction_factor_NO_somata',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[0 .5 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','D1 average portion of each body colocalizing with D2',...
                  'Units', 'normalized',...
                  'Position',[.05 .48 1 .03],...
                  'Tag', 'D1D2_soma_portion_value_mean',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','% of D1 bodies colocalizing with D2',...
                  'Units', 'normalized',...
                  'Position',[.05 .45 1 .03],...
                  'Tag', 'D1D2_tot_percent',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','D1 average portion of each body colocalizing with Darpp',...
                  'Units', 'normalized',...
                  'Position',[.05 .42 1 .03],...
                  'Tag', 'D1Darpp_soma_portion_value_mean',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','% of D1 bodies colocalizing with Darpp',...
                  'Units', 'normalized',...
                  'Position',[.05 .39 1 .03],...
                  'Tag', 'D1Darpp_tot_percent',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Darpp average portion of each body colocalizing with D2',...
                  'Units', 'normalized',...
                  'Position',[.05 .36 1 .03],...
                  'Tag', 'DarppD2_soma_portion_value_mean',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','% of Darpp bodies colocalizing with D2',...
                  'Units', 'normalized',...
                  'Position',[.05 .33 1 .03],...
                  'Tag', 'DarppD2_tot_percent',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Darpp average portion of each body colocalizing with D1',...
                  'Units', 'normalized',...
                  'Position',[.05 .3 1 .03],...
                  'Tag', 'DarppD1_soma_portion_value_mean',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','% of Darpp bodies colocalizing with D1',...
                  'Units', 'normalized',...
                  'Position',[.05 .27 1 .03],...
                  'Tag', 'DarppD1_tot_percent',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','D2 average portion of each body colocalizing with Darpp',...
                  'Units', 'normalized',...
                  'Position',[.05 .24 1 .03],...
                  'Tag', 'D2Darpp_soma_portion_value_mean',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','% of D2 bodies colocalizing with Darpp',...
                  'Units', 'normalized',...
                  'Position',[.05 .21 1 .03],...
                  'Tag', 'D2Darpp_tot_percent',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','D2 average portion of each body colocalizing with D1',...
                  'Units', 'normalized',...
                  'Position',[.05 .18 1 .03],...
                  'Tag', 'D2D1_soma_portion_value_mean',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','% of D2 bodies colocalizing with D1',...
                  'Units', 'normalized',...
                  'Position',[.05 .15 1 .03],...
                  'Tag', 'D2D1_tot_percent',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','D1_DOUBLE_COLOC_percentage',...
                  'Units', 'normalized',...
                  'Position',[.05 .10 1 .03],...
                  'Tag', 'D1_DOUBLE_COLOC_percentage',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','D2_DOUBLE_COLOC_percentage',...
                  'Units', 'normalized',...
                  'Position',[.05 .07 1 .03],...
                  'Tag', 'D2_DOUBLE_COLOC_percentage',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');
              
spcif_var_ans = uicontrol(spcif_var,'Style','radiobutton',...
                  'String','Darpp_DOUBLE_COLOC_percentage',...
                  'Units', 'normalized',...
                  'Position',[.05 .04 1 .03],...
                  'Tag', 'Darpp_DOUBLE_COLOC_percentage',...
                  'BackgroundColor',[.70 .70 .70],...
                  'ForegroundColor',[.5 0 0],...
                  'HandleVisibility','off');              
              
              
              %MAke radio buttons for choosing STATISTICAL TEST
stats_test = uibuttongroup(janela,'Visible','on',...
                  'Position',[.22 .23 .2 .5],...
                  'BackgroundColor',[.7 .7 .7]);
                  %'SelectionChangedFcn',@bselection);
              
set (0, 'DefaultUIControlFontSize', 18);
                  uicontrol(stats_test,...
                      'Style','text',...
                      'ForegroundColor',[1 0 .3],...
                      'BackgroundColor',[.7 .7 .7],...
                      'String', 'Statistics:',...
                      'Units', 'normalized',...
                      'Position',[.025 .6 1 .3]);
                  
                  
   
                 % Create three radio buttons in the button group.
                  set (0, 'DefaultUIControlFontSize', 12);
stats_test_ans = uicontrol(stats_test,'Style','radiobutton',...
                  'String','Check distribution',...
                  'Units', 'normalized',...
                  'Position',[.05 .70 1 .05],...
                  'Tag', 'distrib',...
                  'BackgroundColor',[.7 .7 .7],...
                  'HandleVisibility','off');
              
stats_test_ans = uicontrol(stats_test,'Style','radiobutton',...
                  'String','2 sample T-student',...
                  'Units', 'normalized',...
                  'Position',[.05 .55 1 .05],...
                  'Tag', '2ttest',...
                  'BackgroundColor',[.7 .7 .7],...
                  'HandleVisibility','off');

stats_test_ans = uicontrol(stats_test,'Style','radiobutton',...
                  'String','Mann-Whitney U',...
                  'Units', 'normalized',...
                  'Position',[.05 .4 1 .05],...
                  'Tag', 'mannu',...
                  'BackgroundColor',[.7 .7 .7],...
                  'HandleVisibility','off');
             
stats_test_ans = uicontrol(stats_test,'Style','radiobutton',...
                  'String','One-way ANOVA',...
                  'Units', 'normalized',...
                  'Position',[.05 .25 1 .05],...
                  'Tag', '1anova',...
                  'BackgroundColor',[.7 .7 .7],...
                  'HandleVisibility','off');
              
stats_test_ans = uicontrol(stats_test,'Style','radiobutton',...
                  'String','Kruskal–Wallis H',...
                  'Units', 'normalized',...
                  'Position',[.05 .1 1 .05],...
                  'Tag', 'kruskal',...
                  'BackgroundColor',[.7 .7 .7],...
                  'HandleVisibility','on');
              
         
      set (0, 'DefaultUIControlFontSize', 30);
              %SUBMIT button
              submit_button = uicontrol(janela,'Style','pushbutton',...
                  'String','Submit',...
                  'Units', 'normalized',...
                  'Position',[.23 .075 .175 .125],...
                  'ForegroundColor',[.3 .7 .3],...
                  'Tag', 'submit',...
                  'HandleVisibility','off',...
                  'Callback', {@fetch_ans,brain_part_ans,marker_ans,var_grp_ans,stats_test_ans});
              
      set (0, 'DefaultUIControlFontSize', 10);
              %Close all images button
              close_button = uicontrol(janela,'Style','pushbutton',...
                  'String','Close all figures',...
                  'Units', 'normalized',...
                  'Position',[.825 .125 .130 .06],...
                  'ForegroundColor',[.7 .3 .3],...
                  'Tag', 'close_but',...
                  'HandleVisibility','off',...
                  'Callback', @close_figuras);        
              
              
              
% Make the uibuttongroup visible after creating child objects. 
%marker.Visible = 'on';

    %function bselection(source,event)
     %  display(['Previous: ' event.OldValue.String]);
      % display(['Current: ' event.NewValue.String]);
       %display('------------------');
    %end

function fetch_ans(source,event,brain_part_ans,marker_ans, var_grp_ans,stats_test_ans,group)
anatom=get(get(brain_part,'SelectedObject'),'Tag');    
mark=get(get(marker,'SelectedObject'),'Tag');
vari=get(get(var_grp,'SelectedObject'),'Tag');
    i=1;
    if get(ylcr_ans,'Value') ==1;
        groups{i,1}='YLCR';
        i=i+1;
    end
    if get(yhcr_ans,'Value') ==1;
        groups{i,1}='YHCR';
        i=i+1;
    end    
    if get(olcr_ans,'Value') ==1;
        groups{i,1}='OLCR';
        i=i+1;
    end
    if get(ohcr_ans,'Value') ==1;
        groups{i,1}='OHCR';
    end
    i=1;
    if exist('groups','var') 
        celldisp(groups);
    else
        msgbox('Select at least one study group. These rats dont like to be ignored.');
    end
    subvari=get(get(spcif_var,'SelectedObject'),'Tag');
    test=get(get(stats_test,'SelectedObject'),'Tag');
    stats (anatom, mark, vari, groups, subvari, test);
end

function close_figuras (janela, varargin)
figs = get(0,'children');
figs(figs == gcf) = []; % delete your current figure from the list
close(figs)
end
end
